block_painting.moreblock_shapes = {
  {"micro", "_1"},
  {"panel", "_1"},
  {"micro", "_2"},
  {"panel", "_2"},
  {"micro", "_4"},
  {"panel", "_4"},
  {"micro", ""},
  {"panel", ""},

  {"micro", "_12"},
  {"panel", "_12"},
  {"micro", "_14"},
  {"panel", "_14"},
  {"micro", "_15"},
  {"panel", "_15"},
  {"stair", "_outer"},
  {"stair", ""},

  {"stair", "_inner"},
  {"slab", "_1"},
  {"slab", "_2"},
  {"slab", "_quarter"},
  {"slab", ""},
  {"slab", "_three_quarter"},
  {"slab", "_14"},
  {"slab", "_15"},

  {"slab", "_two_sides"},
  {"slab", "_three_sides"},
  {"slab", "_three_sides_u"},
  {"stair", "_half"},
  {"stair", "_alt_1"},
  {"stair", "_alt_2"},
  {"stair", "_alt_4"},
  {"stair", "_alt"},

  {"slope", ""},
  {"slope", "_half"},
  {"slope", "_half_raised"},
  {"slope", "_inner"},
  {"slope", "_inner_half"},
  {"slope", "_inner_half_raised"},
  {"slope", "_inner_cut"},
  {"slope", "_inner_cut_half"},

  {"slope", "_inner_cut_half_raised"},
  {"slope", "_outer"},
  {"slope", "_outer_half"},
  {"slope", "_outer_half_raised"},
  {"slope", "_outer_cut"},
  {"slope", "_outer_cut_half"},
  {"slope", "_outer_cut_half_raised"},
  {"slope", "_cut"},
}


block_painting.default_nodes = { -- Default stairs/slabs/panels/microblocks:
  "stone",
  "stone_block",
  "cobble",
  "mossycobble",
  "brick",
  "sandstone",
  "steelblock",
  "goldblock",
  "copperblock",
  "bronzeblock",
  "diamondblock",
  "tinblock",
  "desert_stone",
  "desert_stone_block",
  "desert_cobble",
  "meselamp",
  "glass",
  "tree",
  "wood",
  "jungletree",
  "junglewood",
  "pine_tree",
  "pine_wood",
  "acacia_tree",
  "acacia_wood",
  "aspen_tree",
  "aspen_wood",
  "obsidian",
  "obsidian_block",
  "obsidianbrick",
  "obsidian_glass",
  "stonebrick",
  "desert_stonebrick",
  "sandstonebrick",
  "silver_sandstone",
  "silver_sandstone_brick",
  "silver_sandstone_block",
  "desert_sandstone",
  "desert_sandstone_brick",
  "desert_sandstone_block",
  "sandstone_block",
  "coral_skeleton",
  "ice",
}